// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/leadrubix-home/EditorialWhite.tsx": () => import("../components/mockups/leadrubix-home/EditorialWhite.tsx"),
  "./components/mockups/leadrubix-home/PremiumIndigo.tsx": () => import("../components/mockups/leadrubix-home/PremiumIndigo.tsx"),
  "./components/mockups/leadrubix-home/RealEstateEarth.tsx": () => import("../components/mockups/leadrubix-home/RealEstateEarth.tsx")
};
